### ISSUE TITLE
impact_factor未包含在repo中

### ISSUE THREAD

**Issue by paptigshiyf** [ZeroDesigner/eachweek#1]
您好！

judge_pape() 里面用os.popen起了一个impact_factor的程序，获得杂志的影响因子，这一部分的代码可以公开吗？

料想impact_factor也是一个py脚本；更简单地话，直接在eachwork里写个{杂志名：IF}的字典？

**Comment by ZeroDesigner** [comment]
你好，impact_factor是一个安装包，你可以直接使用pip安装，如果你使用conda配置好环境则不需要担心目前的问题。https://pypi.org/project/impact-factor/
